# Generated by Django 3.1.4 on 2021-01-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='no',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='yes',
        ),
    ]
