# Generated by Django 3.1.4 on 2021-01-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210114_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='counter1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='counter2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='element1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='element2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
