# Generated by Django 3.1.4 on 2021-01-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20210114_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='element1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='element2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
