# Generated by Django 3.1.4 on 2021-01-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20210114_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.student'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.student'),
        ),
    ]
