# Generated by Django 3.1.4 on 2021-01-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20210114_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='advisor',
        ),
        migrations.AlterField(
            model_name='administration',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountant', related_query_name='accountant', to='clubs.student'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', related_query_name='agent', to='clubs.student'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', related_query_name='president', to='clubs.student'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', related_query_name='secretary', to='clubs.student'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='vicePresident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vicePresident', related_query_name='vicePresident', to='clubs.student'),
        ),
    ]
