# Generated by Django 3.1.4 on 2021-01-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20210114_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='club',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_date',
        ),
    ]
