# Generated by Django 3.1.4 on 2021-01-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_auto_20210117_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_event',
        ),
    ]
