# Generated by Django 3.1.4 on 2021-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_student_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Engineering', 'Computer Engineering'), ('Software Engineering', 'Software Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Industrial Engineering', 'Industrial Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil  Engineering', 'Civil  Engineering')], max_length=100, null=True),
        ),
    ]
