# Generated by Django 3.1.4 on 2021-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='images/'),
        ),
    ]
