# Generated by Django 3.1.4 on 2021-01-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_auto_20210119_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
